version: '3.9'
services:
    watchtower:
        restart: always
        container_name: watchtower
        command: --include-restarting --label-enable
        image: containrrr/watchtower
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
